## Explore dataset using pandas

In [3]:
import pandas as pd

In [7]:
data = {"Name": ["John","Peter","Lisa"],
       "Age":[25,28,31],
       "Salary":[30000,45000,25000]}

df = pd.DataFrame(data)
print(df)

    Name  Age  Salary
0   John   25   30000
1  Peter   28   45000
2   Lisa   31   25000

In [14]:
data = pd.read_csv("D:/DataAnalytics/SQL by Baraa/sql-ultimate-course-main/datasets/Customers.csv")
print(data)

   CustomerID FirstName  LastName  Country  Score
0           1    Jossef  Goldberg  Germany  350.0
1           2     Kevin     Brown      USA  900.0
2           3      Mary       NaN      USA  750.0
3           4      Mark   Schwarz  Germany  500.0
4           5      Anna     Adams      USA    NaN

In [34]:
data = pd.read_csv("D:/DataAnalytics/dataset for pandas/company.csv")
print(data)

       Name Gender  Salary
0    ayushi      F   20000
1     rohit      M   25000
2  pranjali      F   27000

In [26]:
df = pd.read_excel("python/loan_data_excel.xlsx")
print(df)

            id address_state application_type emp_length  \
0      1077430            GA       INDIVIDUAL   < 1 year
1      1072053            CA       INDIVIDUAL    9 years
2      1069243            CA       INDIVIDUAL    4 years
3      1041756            TX       INDIVIDUAL   < 1 year
4      1068350            IL       INDIVIDUAL  10+ years
...        ...           ...              ...        ...
38571   803452            NJ       INDIVIDUAL   < 1 year
38572   970377            NY       INDIVIDUAL    8 years
38573   875376            CA       INDIVIDUAL    5 years
38574   972997            NY       INDIVIDUAL    5 years
38575   682952            NY       INDIVIDUAL    4 years

                             emp_title grade home_ownership issue_date  \
0                                Ryder     C           RENT 2021-02-11
1                       MKC Accounting     E           RENT 2021-01-01
2                Chemat Technology Inc     C           RENT 2021-01-05
3                  barnes distribution     B       MORTGAGE 2021-02-25
4                        J&J Steel Inc     A       MORTGAGE 2021-01-01
...                                ...   ...            ...        ...
38571         Joseph M Sanzari Company     C       MORTGAGE 2021-07-11
38572                        Swat Fame     C           RENT 2021-10-11
38573  Anaheim Regional Medical Center     D           RENT 2021-09-11
38574               Brooklyn Radiology     D           RENT 2021-10-11
38575                    Allen Edmonds     F           RENT 2021-07-11

      last_credit_pull_date last_payment_date  ... sub_grade        term  \
0                2021-09-13        2021-04-13  ...        C4   60 months
1                2021-12-14        2021-01-15  ...        E1   36 months
2                2021-12-12        2021-01-09  ...        C5   36 months
3                2021-12-12        2021-03-12  ...        B2   60 months
4                2021-12-14        2021-01-15  ...        A1   36 months
...                     ...               ...  ...       ...         ...
38571            2021-05-16        2021-05-16  ...        C1   60 months
38572            2021-04-16        2021-05-16  ...        C1   60 months
38573            2021-05-16        2021-05-16  ...        D5   60 months
38574            2021-05-16        2021-05-16  ...        D5   60 months
38575            2021-05-16        2021-05-16  ...        F3   60 months

       verification_status annual_income     dti installment int_rate  \
0          Source Verified       30000.0  0.0100       59.83   0.1527
1          Source Verified       48000.0  0.0535      109.43   0.1864
2             Not Verified       50000.0  0.2088      421.65   0.1596
3          Source Verified       42000.0  0.0540       97.06   0.1065
4                 Verified       83000.0  0.0231      106.53   0.0603
...                    ...           ...     ...         ...      ...
38571             Verified      100000.0  0.1986      551.64   0.1299
38572             Verified       50000.0  0.0458      579.72   0.1349
38573             Verified       65000.0  0.1734      627.93   0.1749
38574             Verified      368000.0  0.0009      612.72   0.1825
38575             Verified       80000.0  0.0600      486.86   0.2099

       loan_amount  total_acc  total_payment
0             2500          4           1009
1             3000          4           3939
2            12000         11           3522
3             4500          9           4911
4             3500         28           3835
...            ...        ...            ...
38571        24250         33          31946
38572        25200         18          31870
38573        25000         20          35721
38574        24000          9          33677
38575        18000          7          27679

[38576 rows x 24 columns]

In [27]:
df.shape # shows no of Rows and Columns in the dataframe

(38576, 24)

In [29]:
print(df.head(10)) # default shows 5 values
print(df.tail(10)) # default shows 5 values

        id address_state application_type emp_length              emp_title  \
0  1077430            GA       INDIVIDUAL   < 1 year                  Ryder
1  1072053            CA       INDIVIDUAL    9 years         MKC Accounting
2  1069243            CA       INDIVIDUAL    4 years  Chemat Technology Inc
3  1041756            TX       INDIVIDUAL   < 1 year    barnes distribution
4  1068350            IL       INDIVIDUAL  10+ years          J&J Steel Inc
5  1062608            CA       INDIVIDUAL    3 years         Studio 94 Corp
6  1067441            TX       INDIVIDUAL  10+ years      American Airlines
7  1066424            PA       INDIVIDUAL  10+ years            SCI Mahanoy
8  1065254            FL       INDIVIDUAL  10+ years         Tech Data Corp
9  1064589            MI       INDIVIDUAL  10+ years     teltow contracting

  grade home_ownership issue_date last_credit_pull_date last_payment_date  \
0     C           RENT 2021-02-11            2021-09-13        2021-04-13
1     E           RENT 2021-01-01            2021-12-14        2021-01-15
2     C           RENT 2021-01-05            2021-12-12        2021-01-09
3     B       MORTGAGE 2021-02-25            2021-12-12        2021-03-12
4     A       MORTGAGE 2021-01-01            2021-12-14        2021-01-15
5     C           RENT 2021-07-17            2021-03-16        2021-08-12
6     C       MORTGAGE 2021-11-19            2021-06-14        2021-12-13
7     A            OWN 2021-06-11            2021-07-14        2021-07-14
8     A       MORTGAGE 2021-09-02            2021-06-15        2021-10-12
9     B       MORTGAGE 2021-02-09            2021-03-16        2021-03-16

   ... sub_grade        term  verification_status annual_income     dti  \
0  ...        C4   60 months      Source Verified       30000.0  0.0100
1  ...        E1   36 months      Source Verified       48000.0  0.0535
2  ...        C5   36 months         Not Verified       50000.0  0.2088
3  ...        B2   60 months      Source Verified       42000.0  0.0540
4  ...        A1   36 months             Verified       83000.0  0.0231
5  ...        C3   36 months         Not Verified       28000.0  0.1260
6  ...        C2   36 months             Verified       94800.0  0.2453
7  ...        A4   36 months      Source Verified       59000.0  0.0665
8  ...        A5   36 months             Verified      116400.0  0.0394
9  ...        B5   60 months         Not Verified       36000.0  0.1773

  installment int_rate  loan_amount  total_acc  total_payment
0       59.83   0.1527         2500          4           1009
1      109.43   0.1864         3000          4           3939
2      421.65   0.1596        12000         11           3522
3       97.06   0.1065         4500          9           4911
4      106.53   0.0603         3500         28           3835
5      275.96   0.1465         8000         11           8637
6      205.86   0.1427         6000         30           7218
7      172.10   0.0790         5500         23           6172
8      762.08   0.0890        24000         31           8650
9       93.21   0.1269         4125         21           5551

[10 rows x 24 columns]
            id address_state application_type emp_length  \
38566  1007647            VA       INDIVIDUAL     1 year
38567  1020423            GA       INDIVIDUAL   < 1 year
38568   792945            IL       INDIVIDUAL    3 years
38569   844956            VA       INDIVIDUAL    2 years
38570   841271            CT       INDIVIDUAL     1 year
38571   803452            NJ       INDIVIDUAL   < 1 year
38572   970377            NY       INDIVIDUAL    8 years
38573   875376            CA       INDIVIDUAL    5 years
38574   972997            NY       INDIVIDUAL    5 years
38575   682952            NY       INDIVIDUAL    4 years

                                      emp_title grade home_ownership  \
38566  Ebert & Baumann Consulting Engineers, In     C           RENT
38567                            Triton Digital     D           RENT
38568                                  Intertek     E           RENT
38569                                      SAIC     G           RENT
38570                                 Travelers     D       MORTGAGE
38571                  Joseph M Sanzari Company     C       MORTGAGE
38572                                 Swat Fame     C           RENT
38573           Anaheim Regional Medical Center     D           RENT
38574                        Brooklyn Radiology     D           RENT
38575                             Allen Edmonds     F           RENT

      issue_date last_credit_pull_date last_payment_date  ... sub_grade  \
38566 2021-11-11            2021-05-16        2021-05-16  ...        C1
38567 2021-11-11            2021-05-16        2021-05-16  ...        D3
38568 2021-06-11            2021-05-16        2021-05-16  ...        E2
38569 2021-08-11            2021-05-16        2021-05-16  ...        G1
38570 2021-08-11            2021-04-16        2021-05-16  ...        D2
38571 2021-07-11            2021-05-16        2021-05-16  ...        C1
38572 2021-10-11            2021-04-16        2021-05-16  ...        C1
38573 2021-09-11            2021-05-16        2021-05-16  ...        D5
38574 2021-10-11            2021-05-16        2021-05-16  ...        D5
38575 2021-07-11            2021-05-16        2021-05-16  ...        F3

             term  verification_status annual_income     dti installment  \
38566   60 months      Source Verified       72000.0  0.0117      345.08
38567   60 months      Source Verified       43500.0  0.0041      164.99
38568   60 months      Source Verified       57040.5  0.0496      512.13
38569   60 months      Source Verified      150000.0  0.0888      113.50
38570   60 months      Source Verified       56000.0  0.1200      291.76
38571   60 months             Verified      100000.0  0.1986      551.64
38572   60 months             Verified       50000.0  0.0458      579.72
38573   60 months             Verified       65000.0  0.1734      627.93
38574   60 months             Verified      368000.0  0.0009      612.72
38575   60 months             Verified       80000.0  0.0600      486.86

      int_rate  loan_amount  total_acc  total_payment
38566   0.1349        15000          7          18588
38567   0.1727         6600          9           8890
38568   0.1839        20000         20          29702
38569   0.2211         4100         29           6463
38570   0.1599        12000         18          16587
38571   0.1299        24250         33          31946
38572   0.1349        25200         18          31870
38573   0.1749        25000         20          35721
38574   0.1825        24000          9          33677
38575   0.2099        18000          7          27679

[10 rows x 24 columns]

In [33]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     38576 non-null  int64
 1   address_state          38576 non-null  object
 2   application_type       38576 non-null  object
 3   emp_length             38576 non-null  object
 4   emp_title              37138 non-null  object
 5   grade                  38576 non-null  object
 6   home_ownership         38576 non-null  object
 7   issue_date             38576 non-null  datetime64[ns]
 8   last_credit_pull_date  38576 non-null  datetime64[ns]
 9   last_payment_date      38576 non-null  datetime64[ns]
 10  loan_status            38576 non-null  object
 11  next_payment_date      38576 non-null  datetime64[ns]
 12  member_id              38576 non-null  int64
 13  purpose                38576 non-null  object
 14  sub_grade              38576 non-null  object
 15  term                   38576 non-null  object
 16  verification_status    38576 non-null  object
 17  annual_income          38576 non-null  float64
 18  dti                    38576 non-null  float64
 19  installment            38576 non-null  float64
 20  int_rate               38576 non-null  float64
 21  loan_amount            38576 non-null  int64
 22  total_acc              38576 non-null  int64
 23  total_payment          38576 non-null  int64
dtypes: datetime64[ns](4), float64(4), int64(5), object(11)
memory usage: 7.1+ MB
None

In [35]:
df.describe()

,id,issue_date,last_credit_pull_date,last_payment_date,next_payment_date,member_id,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
count,3.857600e+04,38576,38576,38576,38576,3.857600e+04,3.857600e+04,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000
mean,6.810371e+05,2021-07-16 02:31:35.562007040,2021-06-08 13:36:34.193280512,2021-06-26 09:52:08.909166080,2021-07-26 20:42:20.605557760,8.476515e+05,6.964454e+04,0.133274,326.862965,0.120488,11296.066855,22.132544,12263.348533
min,5.473400e+04,2021-01-01 00:00:00,2021-01-08 00:00:00,2021-01-08 00:00:00,2021-02-08 00:00:00,7.069900e+04,4.000000e+03,0.000000,15.690000,0.054200,500.000000,2.000000,34.000000
25%,5.135170e+05,2021-04-11 00:00:00,2021-04-15 00:00:00,2021-03-16 00:00:00,2021-04-16 00:00:00,6.629788e+05,4.150000e+04,0.082100,168.450000,0.093200,5500.000000,14.000000,5633.000000
50%,6.627280e+05,2021-07-11 00:00:00,2021-05-16 00:00:00,2021-06-14 00:00:00,2021-07-14 00:00:00,8.473565e+05,6.000000e+04,0.134200,283.045000,0.118600,10000.000000,20.000000,10042.000000
75%,8.365060e+05,2021-10-11 00:00:00,2021-08-13 00:00:00,2021-09-15 00:00:00,2021-10-15 00:00:00,1.045652e+06,8.320050e+04,0.185900,434.442500,0.145900,15000.000000,29.000000,16658.000000
max,1.077501e+06,2021-12-12 00:00:00,2022-01-20 00:00:00,2021-12-15 00:00:00,2022-01-15 00:00:00,1.314167e+06,6.000000e+06,0.299900,1305.190000,0.245900,35000.000000,90.000000,58564.000000
std,2.113246e+05,NaN,NaN,NaN,NaN,2.668105e+05,6.429368e+04,0.066662,209.092000,0.037164,7460.746022,11.392282,9051.104777

In [36]:
print(df.isnull().sum())

id                          0
address_state               0
application_type            0
emp_length                  0
emp_title                1438
grade                       0
home_ownership              0
issue_date                  0
last_credit_pull_date       0
last_payment_date           0
loan_status                 0
next_payment_date           0
member_id                   0
purpose                     0
sub_grade                   0
term                        0
verification_status         0
annual_income               0
dti                         0
installment                 0
int_rate                    0
loan_amount                 0
total_acc                   0
total_payment               0
dtype: int64

In [5]:
# Find duplicate data
data = pd.read_excel("python\company1.xlsx")
print(data)

    EEID      Name Gender   Salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01   aayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [46]:
print(data["EEID"].duplicated().sum())

2

In [48]:
print(data.isnull().sum())

EEID      0
Name      1
Gender    0
Salary    2
dtype: int64

In [52]:
print(data.dropna())

    EEID     Name Gender   Salary
1  EMP02    rohit      M  25000.0
3  EMP01  aayushi      F  20000.0
6  EMP02    rohit      M  25000.0

In [53]:
print(data)

    EEID      Name Gender   Salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01   aayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [54]:
import numpy as np
print(data.replace(np.nan,30000))

    EEID      Name Gender   Salary
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali  30000  27000.0
3  EMP01   aayushi      F  20000.0
4  EMP05     30000      M  25000.0
5  EMP06     rohit      M  30000.0
6  EMP02     rohit      M  25000.0

In [64]:
data["Salary"] = data["Salary"].replace(np.nan,24400)
print(data)
print(data["Salary"].mean())

    EEID      Name Gender   Salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01   aayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0
24400.0

In [6]:
print(data["Salary"].mean())

24400.0

In [10]:
print(data)

    EEID      Name Gender   Salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01   aayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [12]:
print(data.bfill())

    EEID      Name Gender   Salary
0  EMP01    ayushi      F  25000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      F  27000.0
3  EMP01   aayushi      F  20000.0
4  EMP05     rohit      M  25000.0
5  EMP06     rohit      M  25000.0
6  EMP02     rohit      M  25000.0

In [14]:
print(data.ffill())

    EEID      Name Gender   Salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      M  27000.0
3  EMP01   aayushi      F  20000.0
4  EMP05   aayushi      M  25000.0
5  EMP06     rohit      M  25000.0
6  EMP02     rohit      M  25000.0

## Columns Transformation

In [6]:
import openpyxl

In [8]:
data = pd.read_excel("D:/DataAnalytics/dataset for pandas/ESD.xlsx")
print(data)

       EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT
1    E04105    Theodore Dinh       Technical Architect          IT
2    E02572     Luna Sanders                  Director     Finance
3    E02832  Penelope Jordan  Computer Systems Manager          IT
4    E01639        Austin Vo               Sr. Analyst     Finance
..      ...              ...                       ...         ...
995  E03094     Wesley Young               Sr. Analyst   Marketing
996  E01909     Lillian Khan                   Analyst     Finance
997  E04398      Oliver Yang                  Director   Marketing
998  E02521      Lily Nguyen               Sr. Analyst     Finance
999  E03545      Sofia Cheng            Vice President  Accounting

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604
1             Manufacturing    Male      Asian   59 1997-11-29          99975
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913
4             Manufacturing    Male      Asian   55 1995-11-20          95409
..                      ...     ...        ...  ...        ...            ...
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427
996     Speciality Products  Female      Asian   44 2010-05-31          47387
997     Speciality Products    Male      Asian   31 2019-06-10         176710
998     Speciality Products  Female      Asian   33 2012-01-28          95960
999               Corporate  Female      Asian   63 2020-07-26         216195

     Bonus %        Country       City  Exit Date
0       0.15  United States    Seattle 2021-10-16
1       0.00          China  Chongqing        NaT
2       0.20  United States    Chicago        NaT
3       0.07  United States    Chicago        NaT
4       0.00  United States    Phoenix        NaT
..       ...            ...        ...        ...
995     0.00  United States   Columbus        NaT
996     0.00          China    Chengdu 2018-01-08
997     0.15  United States      Miami        NaT
998     0.00          China    Chengdu        NaT
999     0.31  United States      Miami        NaT

[1000 rows x 14 columns]

In [10]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EEID           1000 non-null   object
 1   Full Name      1000 non-null   object
 2   Job Title      1000 non-null   object
 3   Department     1000 non-null   object
 4   Business Unit  1000 non-null   object
 5   Gender         1000 non-null   object
 6   Ethnicity      1000 non-null   object
 7   Age            1000 non-null   int64
 8   Hire Date      1000 non-null   datetime64[ns]
 9   Annual Salary  1000 non-null   int64
 10  Bonus %        1000 non-null   float64
 11  Country        1000 non-null   object
 12  City           1000 non-null   object
 13  Exit Date      85 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2), object(9)
memory usage: 109.5+ KB
None

In [11]:
print(data.describe())

               Age                   Hire Date  Annual Salary      Bonus %  \
count  1000.000000                        1000    1000.000000  1000.000000
mean     44.382000  2012-04-07 02:54:14.400000  113217.365000     0.088660
min      25.000000         1992-01-09 00:00:00   40063.000000     0.000000
25%      35.000000         2007-02-14 00:00:00   71430.250000     0.000000
50%      45.000000         2014-02-15 12:00:00   96557.000000     0.000000
75%      54.000000         2018-06-22 00:00:00  150782.250000     0.150000
max      65.000000         2021-12-26 00:00:00  258498.000000     0.400000
std      11.246981                         NaN   53545.985644     0.117856

                           Exit Date
count                             85
mean   2016-11-02 18:04:14.117647104
min              1994-12-18 00:00:00
25%              2014-12-25 00:00:00
50%              2019-05-23 00:00:00
75%              2021-04-09 00:00:00
max              2022-08-17 00:00:00
std                              NaN

In [14]:
print(data.isnull().sum())

EEID               0
Full Name          0
Job Title          0
Department         0
Business Unit      0
Gender             0
Ethnicity          0
Age                0
Hire Date          0
Annual Salary      0
Bonus %            0
Country            0
City               0
Exit Date        915
dtype: int64

In [18]:
data.head(21)

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT
5,E00644,Joshua Gupta,Account Representative,Sales,Corporate,Male,Asian,57,2017-01-24,50994,0.00,China,Chongqing,NaT
6,E01550,Ruby Barnes,Manager,IT,Corporate,Female,Caucasian,27,2020-07-01,119746,0.10,United States,Phoenix,NaT
7,E04332,Luke Martin,Analyst,Finance,Manufacturing,Male,Black,25,2020-05-16,41336,0.00,United States,Miami,2021-05-20
8,E04533,Easton Bailey,Manager,Accounting,Manufacturing,Male,Caucasian,29,2019-01-25,113527,0.06,United States,Austin,NaT
9,E03838,Madeline Walker,Sr. Analyst,Finance,Speciality Products,Female,Caucasian,34,2018-06-13,77203,0.00,United States,Chicago,NaT
10,E00591,Savannah Ali,Sr. Manger,Human Resources,Manufacturing,Female,Asian,36,2009-02-11,157333,0.15,United States,Miami,NaT
11,E03344,Camila Rogers,Controls Engineer,Engineering,Speciality Products,Female,Caucasian,27,2021-10-21,109851,0.00,United States,Seattle,NaT
12,E00530,Eli Jones,Manager,Human Resources,Manufacturing,Male,Caucasian,59,1999-03-14,105086,0.09,United States,Austin,NaT
13,E04239,Everleigh Ng,Sr. Manger,Finance,Research & Development,Female,Asian,51,2021-06-10,146742,0.10,China,Shanghai,NaT
14,E03496,Robert Yang,Sr. Analyst,Accounting,Speciality Products,Male,Asian,31,2017-11-04,97078,0.00,United States,Austin,2020-03-09
15,E00549,Isabella Xi,Vice President,Marketing,Research & Development,Female,Asian,41,2013-03-13,249270,0.30,United States,Seattle,NaT
16,E00163,Bella Powell,Director,Finance,Research & Development,Female,Black,65,2002-03-04,175837,0.20,United States,Phoenix,NaT
17,E00884,Camila Silva,Sr. Manger,Marketing,Speciality Products,Female,Latino,64,2003-12-01,154828,0.13,United States,Seattle,NaT
18,E04116,David Barnes,Director,IT,Corporate,Male,Caucasian,64,2013-11-03,186503,0.24,United States,Columbus,NaT
19,E04625,Adam Dang,Director,Sales,Research & Development,Male,Asian,45,2002-07-09,166331,0.18,China,Chongqing,NaT
20,E03680,Elias Alvarado,Sr. Manger,IT,Manufacturing,Male,Latino,56,2012-01-09,146140,0.10,Brazil,Manaus,NaT

In [19]:
data.tail(21)

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
979,E00287,Maverick Figueroa,IT Systems Architect,IT,Corporate,Male,Latino,48,2008-07-06,94815,0.00,United States,Chicago,NaT
980,E00785,Hannah Hoang,Manager,Accounting,Speciality Products,Female,Asian,25,2021-12-15,114893,0.06,China,Chengdu,NaT
981,E04598,Violet Garcia,Sr. Analyst,Marketing,Speciality Products,Female,Latino,35,2017-01-10,80622,0.00,United States,Austin,NaT
982,E03247,Aaliyah Mai,Vice President,IT,Speciality Products,Female,Asian,57,2016-11-11,246589,0.33,United States,Phoenix,2017-03-26
983,E02703,Austin Vang,Manager,Marketing,Speciality Products,Male,Asian,49,2018-05-20,119397,0.09,China,Beijing,2019-03-14
984,E02191,Maria Sun,Director,Sales,Corporate,Female,Asian,25,2021-12-19,150666,0.23,China,Chengdu,NaT
985,E00156,Madelyn Scott,Sr. Manger,IT,Research & Development,Female,Caucasian,46,2002-01-09,148035,0.14,United States,Phoenix,NaT
986,E03349,Dylan Chin,Director,Finance,Corporate,Male,Asian,60,2017-06-05,158898,0.18,United States,Miami,NaT
987,E04032,Emery Zhang,Field Engineer,Engineering,Corporate,Female,Asian,45,2012-02-28,89659,0.00,China,Beijing,NaT
988,E00005,Riley Washington,Director,Sales,Speciality Products,Female,Caucasian,39,2007-04-29,171487,0.23,United States,Phoenix,NaT
989,E04354,Raelynn Rios,Vice President,Sales,Manufacturing,Female,Latino,43,2016-08-21,258498,0.35,United States,Columbus,NaT
990,E01578,Anthony Hong,Sr. Manger,IT,Research & Development,Male,Asian,37,2010-11-29,146961,0.11,United States,Columbus,NaT
991,E03430,Leo Herrera,Sr. Business Partner,Human Resources,Research & Development,Male,Latino,48,1998-04-22,85369,0.00,Brazil,Manaus,2004-11-27
992,E03058,Robert Wright,Technical Architect,IT,Manufacturing,Male,Caucasian,30,2015-06-14,67489,0.00,United States,Chicago,NaT
993,E04762,Audrey Richardson,Director,IT,Manufacturing,Female,Caucasian,46,2018-10-06,166259,0.17,United States,Chicago,NaT
994,E01148,Scarlett Kumar,Systems Analyst,IT,Corporate,Female,Asian,55,2009-01-07,47032,0.00,United States,Columbus,NaT
995,E03094,Wesley Young,Sr. Analyst,Marketing,Speciality Products,Male,Caucasian,33,2016-09-18,98427,0.00,United States,Columbus,NaT
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44,2010-05-31,47387,0.00,China,Chengdu,2018-01-08
997,E04398,Oliver Yang,Director,Marketing,Speciality Products,Male,Asian,31,2019-06-10,176710,0.15,United States,Miami,NaT
998,E02521,Lily Nguyen,Sr. Analyst,Finance,Speciality Products,Female,Asian,33,2012-01-28,95960,0.00,China,Chengdu,NaT
999,E03545,Sofia Cheng,Vice President,Accounting,Corporate,Female,Asian,63,2020-07-26,216195,0.31,United States,Miami,NaT

In [28]:
print(data["EEID"].min())

E00005

In [75]:
df = pd.read_excel("D:/DataAnalytics/dataset for pandas/ESD.xlsx")
print(df)

       EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT
1    E04105    Theodore Dinh       Technical Architect          IT
2    E02572     Luna Sanders                  Director     Finance
3    E02832  Penelope Jordan  Computer Systems Manager          IT
4    E01639        Austin Vo               Sr. Analyst     Finance
..      ...              ...                       ...         ...
995  E03094     Wesley Young               Sr. Analyst   Marketing
996  E01909     Lillian Khan                   Analyst     Finance
997  E04398      Oliver Yang                  Director   Marketing
998  E02521      Lily Nguyen               Sr. Analyst     Finance
999  E03545      Sofia Cheng            Vice President  Accounting

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604
1             Manufacturing    Male      Asian   59 1997-11-29          99975
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913
4             Manufacturing    Male      Asian   55 1995-11-20          95409
..                      ...     ...        ...  ...        ...            ...
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427
996     Speciality Products  Female      Asian   44 2010-05-31          47387
997     Speciality Products    Male      Asian   31 2019-06-10         176710
998     Speciality Products  Female      Asian   33 2012-01-28          95960
999               Corporate  Female      Asian   63 2020-07-26         216195

     Bonus %        Country       City  Exit Date
0       0.15  United States    Seattle 2021-10-16
1       0.00          China  Chongqing        NaT
2       0.20  United States    Chicago        NaT
3       0.07  United States    Chicago        NaT
4       0.00  United States    Phoenix        NaT
..       ...            ...        ...        ...
995     0.00  United States   Columbus        NaT
996     0.00          China    Chengdu 2018-01-08
997     0.15  United States      Miami        NaT
998     0.00          China    Chengdu        NaT
999     0.31  United States      Miami        NaT

[1000 rows x 14 columns]

In [76]:
df.loc[(df["Bonus %"] == 0, "GetBonus")] = "No Bonus"
df.loc[(df["Bonus %"] > 0, "GetBonus")] = "Bonus"
print(df.head(10))

     EEID        Full Name                 Job Title  Department  \
0  E02387      Emily Davis                Sr. Manger          IT
1  E04105    Theodore Dinh       Technical Architect          IT
2  E02572     Luna Sanders                  Director     Finance
3  E02832  Penelope Jordan  Computer Systems Manager          IT
4  E01639        Austin Vo               Sr. Analyst     Finance
5  E00644     Joshua Gupta    Account Representative       Sales
6  E01550      Ruby Barnes                   Manager          IT
7  E04332      Luke Martin                   Analyst     Finance
8  E04533    Easton Bailey                   Manager  Accounting
9  E03838  Madeline Walker               Sr. Analyst     Finance

            Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0  Research & Development  Female      Black   55 2016-04-08         141604
1           Manufacturing    Male      Asian   59 1997-11-29          99975
2     Speciality Products  Female  Caucasian   50 2006-10-26         163099
3           Manufacturing  Female  Caucasian   26 2019-09-27          84913
4           Manufacturing    Male      Asian   55 1995-11-20          95409
5               Corporate    Male      Asian   57 2017-01-24          50994
6               Corporate  Female  Caucasian   27 2020-07-01         119746
7           Manufacturing    Male      Black   25 2020-05-16          41336
8           Manufacturing    Male  Caucasian   29 2019-01-25         113527
9     Speciality Products  Female  Caucasian   34 2018-06-13          77203

   Bonus %        Country       City  Exit Date  GetBonus
0     0.15  United States    Seattle 2021-10-16     Bonus
1     0.00          China  Chongqing        NaT  No Bonus
2     0.20  United States    Chicago        NaT     Bonus
3     0.07  United States    Chicago        NaT     Bonus
4     0.00  United States    Phoenix        NaT  No Bonus
5     0.00          China  Chongqing        NaT  No Bonus
6     0.10  United States    Phoenix        NaT     Bonus
7     0.00  United States      Miami 2021-05-20  No Bonus
8     0.06  United States     Austin        NaT     Bonus
9     0.00  United States    Chicago        NaT  No Bonus

In [53]:
print(df["Department"].value_counts())

Department
IT                 241
Engineering        158
Sales              140
Human Resources    125
Finance            120
Marketing          120
Accounting          96
Name: count, dtype: int64

In [60]:
print(df["Country"].value_counts())

Country
United States    643
China            218
Brazil           139
Name: count, dtype: int64

In [48]:
print(df["GetBonus"].value_counts())

GetBonus
No Bonus    525
Bonus       475
Name: count, dtype: int64

In [61]:
df.value_counts(["Country", "City"])

Country        City
United States  Seattle           118
               Columbus          113
               Miami             112
               Phoenix           109
               Austin             99
               Chicago            92
China          Chongqing          65
               Beijing            55
Brazil         Sao Paulo          53
China          Shanghai           52
               Chengdu            46
Brazil         Rio de Janerio     44
               Manaus             42
Name: count, dtype: int64

In [62]:
df.value_counts("City")

City
Seattle           118
Columbus          113
Miami             112
Phoenix           109
Austin             99
Chicago            92
Chongqing          65
Beijing            55
Sao Paulo          53
Shanghai           52
Chengdu            46
Rio de Janerio     44
Manaus             42
Name: count, dtype: int64

In [64]:
df["Full Name"] = df.

       EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT
1    E04105    Theodore Dinh       Technical Architect          IT
2    E02572     Luna Sanders                  Director     Finance
3    E02832  Penelope Jordan  Computer Systems Manager          IT
4    E01639        Austin Vo               Sr. Analyst     Finance
..      ...              ...                       ...         ...
995  E03094     Wesley Young               Sr. Analyst   Marketing
996  E01909     Lillian Khan                   Analyst     Finance
997  E04398      Oliver Yang                  Director   Marketing
998  E02521      Lily Nguyen               Sr. Analyst     Finance
999  E03545      Sofia Cheng            Vice President  Accounting

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604
1             Manufacturing    Male      Asian   59 1997-11-29          99975
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913
4             Manufacturing    Male      Asian   55 1995-11-20          95409
..                      ...     ...        ...  ...        ...            ...
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427
996     Speciality Products  Female      Asian   44 2010-05-31          47387
997     Speciality Products    Male      Asian   31 2019-06-10         176710
998     Speciality Products  Female      Asian   33 2012-01-28          95960
999               Corporate  Female      Asian   63 2020-07-26         216195

     Bonus %        Country       City  Exit Date  GetBonus
0       0.15  United States    Seattle 2021-10-16     Bonus
1       0.00          China  Chongqing        NaT  No Bonus
2       0.20  United States    Chicago        NaT     Bonus
3       0.07  United States    Chicago        NaT     Bonus
4       0.00  United States    Phoenix        NaT  No Bonus
..       ...            ...        ...        ...       ...
995     0.00  United States   Columbus        NaT  No Bonus
996     0.00          China    Chengdu 2018-01-08  No Bonus
997     0.15  United States      Miami        NaT     Bonus
998     0.00          China    Chengdu        NaT  No Bonus
999     0.31  United States      Miami        NaT     Bonus

[1000 rows x 15 columns]

In [95]:
df = pd.read_csv("D:/DataAnalytics/SQL by Baraa/sql-ultimate-course-main/datasets/Employees.csv")
print(df)

   EmployeeID FirstName LastName Department   BirthDate Gender  Salary  \
0           1     Frank      Lee  Marketing  1988-12-05      M   55000
1           2     Kevin    Brown  Marketing  1972-11-25      M   65000
2           3      Mary      NaN      Sales  1986-01-05      F   75000
3           4   Michael      Ray      Sales  1977-02-10      M   90000
4           5     Carol    Baker      Sales  1982-02-11      F   55000

   ManagerID
0        NaN
1        1.0
2        1.0
3        2.0
4        3.0

In [96]:
df["Full Name"] = df["FirstName"].str.upper() + " " + df["LastName"].str.upper()
print(df)

   EmployeeID FirstName LastName Department   BirthDate Gender  Salary  \
0           1     Frank      Lee  Marketing  1988-12-05      M   55000
1           2     Kevin    Brown  Marketing  1972-11-25      M   65000
2           3      Mary      NaN      Sales  1986-01-05      F   75000
3           4   Michael      Ray      Sales  1977-02-10      M   90000
4           5     Carol    Baker      Sales  1982-02-11      F   55000

   ManagerID    Full Name
0        NaN    FRANK LEE
1        1.0  KEVIN BROWN
2        1.0          NaN
3        2.0  MICHAEL RAY
4        3.0  CAROL BAKER

In [78]:
data = pd.read_excel("D:/DataAnalytics/dataset for pandas/practice_1.xlsx")
print(data)

  First Name  Last Name  Salary EEID
0       ross  tribbiani   20000   E1
1     rachel       bing   40000   E2
2     monica      green   25000   E7
3       joey     geller   60000   E8
4   chandler     buffay   33000   E4
5     phoebe       bing   45000   E5

In [81]:
data["Bonus"] = (data["Salary"]/100)*20
print(data)

  First Name  Last Name  Salary EEID    Bonus
0       ross  tribbiani   20000   E1   4000.0
1     rachel       bing   40000   E2   8000.0
2     monica      green   25000   E7   5000.0
3       joey     geller   60000   E8  12000.0
4   chandler     buffay   33000   E4   6600.0
5     phoebe       bing   45000   E5   9000.0

In [83]:
data = {"Months": ["January","February","March","April"]}

a = pd.DataFrame(data)
print(a)

     Months
0   January
1  February
2     March
3     April

In [93]:
def extract(value):
    return value[0:3]

a["Short Months"] = a["Months"].map(extract)
print(a)

     Months Short Months
0   January          Jan
1  February          Feb
2     March          Mar
3     April          Apr
     Months
0   January
1  February
2     March
3     April

In [105]:
df = pd.read_excel("D:/DataAnalytics/dataset for pandas/ESD.xlsx")
print(df)

       EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT
1    E04105    Theodore Dinh       Technical Architect          IT
2    E02572     Luna Sanders                  Director     Finance
3    E02832  Penelope Jordan  Computer Systems Manager          IT
4    E01639        Austin Vo               Sr. Analyst     Finance
..      ...              ...                       ...         ...
995  E03094     Wesley Young               Sr. Analyst   Marketing
996  E01909     Lillian Khan                   Analyst     Finance
997  E04398      Oliver Yang                  Director   Marketing
998  E02521      Lily Nguyen               Sr. Analyst     Finance
999  E03545      Sofia Cheng            Vice President  Accounting

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604
1             Manufacturing    Male      Asian   59 1997-11-29          99975
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913
4             Manufacturing    Male      Asian   55 1995-11-20          95409
..                      ...     ...        ...  ...        ...            ...
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427
996     Speciality Products  Female      Asian   44 2010-05-31          47387
997     Speciality Products    Male      Asian   31 2019-06-10         176710
998     Speciality Products  Female      Asian   33 2012-01-28          95960
999               Corporate  Female      Asian   63 2020-07-26         216195

     Bonus %        Country       City  Exit Date
0       0.15  United States    Seattle 2021-10-16
1       0.00          China  Chongqing        NaT
2       0.20  United States    Chicago        NaT
3       0.07  United States    Chicago        NaT
4       0.00  United States    Phoenix        NaT
..       ...            ...        ...        ...
995     0.00  United States   Columbus        NaT
996     0.00          China    Chengdu 2018-01-08
997     0.15  United States      Miami        NaT
998     0.00          China    Chengdu        NaT
999     0.31  United States      Miami        NaT

[1000 rows x 14 columns]

In [118]:
gp = df.groupby(["Department", "Gender"]).agg({"Annual Salary":"sum"})
print(gp)

                        Annual Salary
Department      Gender
Accounting      Female        6914128
                Male          4907979
Engineering     Female        8377656
                Male          8849907
Finance         Female        8424540
                Male          6311807
Human Resources Female        7693326
                Male          7063979
IT              Female       11344574
                Male         12222925
Marketing       Female        7145899
                Male          8413665
Sales           Female        8278622
                Male          7268358

In [120]:
print(df[(df["Department"]=="Accounting") & (df["Gender"]=="Female")]["Annual Salary"].sum())
print(df[(df["Department"]=="Accounting") & (df["Gender"]=="Male")]["Annual Salary"].sum())

6914128
4907979

In [121]:
gp = df.groupby(["Department","Gender","Country"]).agg({"EEID":"count"})
print(gp)

                                      EEID
Department      Gender Country
Accounting      Female Brazil            7
                       China            10
                       United States    36
                Male   Brazil            3
                       China            10
                       United States    30
Engineering     Female Brazil           17
                       China            17
                       United States    46
                Male   Brazil           15
                       China            12
                       United States    51
Finance         Female Brazil            9
                       China            19
                       United States    41
                Male   Brazil            9
                       China             9
                       United States    33
Human Resources Female Brazil           11
                       China            12
                       United States    41
                Male   Brazil            8
                       China            13
                       United States    40
IT              Female Brazil           12
                       China            22
                       United States    85
                Male   Brazil           14
                       China            28
                       United States    80
Marketing       Female Brazil            6
                       China            14
                       United States    37
                Male   Brazil            7
                       China            21
                       United States    35
Sales           Female Brazil           13
                       China            15
                       United States    48
                Male   Brazil            8
                       China            16
                       United States    40

In [123]:
gp1 = df.groupby("Country").agg({"Age":"mean"})
print(gp1)

                     Age
Country
Brazil         43.654676
China          45.389908
United States  44.197512

In [125]:
gp1 = df.groupby(["Country","Gender"]).agg({"Annual Salary":"max"})
print(gp1)

                      Annual Salary
Country       Gender
Brazil        Female         258426
              Male           249506
China         Female         249686
              Male           257194
United States Female         258498
              Male           258081

In [127]:
gp1 = df.groupby(["Country","Gender"]).agg({"Annual Salary":"min"})
print(gp1)

                      Annual Salary
Country       Gender
Brazil        Female          44735
              Male            40316
China         Female          46833
              Male            41728
United States Female          40124
              Male            40063

In [128]:
gp1 = df.groupby(["Country","Gender"]).agg({"Annual Salary":"max","Age":"min"})
print(gp1)

                      Annual Salary  Age
Country       Gender
Brazil        Female         258426   25
              Male           249506   26
China         Female         249686   25
              Male           257194   25
United States Female         258498   25
              Male           258081   25

In [136]:
data1 = {"Emp Id": ["E01","E02","E03","E04","E05","E06"],
        "Names":["Ram","Shyam","Rahul","Vishal","Ravi","John"],
        "Age":[34,56,23,44,32,36]}

data2= {"Emp Id": ["E01","E07","E03","E04","E08","E06"],
       "Salary":[45000,56000,34000,30000,50000,62000]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
print(df1,"\n")
print(df2)

  Emp Id   Names  Age
0    E01     Ram   34
1    E02   Shyam   56
2    E03   Rahul   23
3    E04  Vishal   44
4    E05    Ravi   32
5    E06    John   36

  Emp Id  Salary
0    E01   45000
1    E07   56000
2    E03   34000
3    E04   30000
4    E08   50000
5    E06   62000

In [140]:
print(pd.merge(df1,df2,on = "Emp Id", how = "left"))

  Emp Id   Names  Age   Salary
0    E01     Ram   34  45000.0
1    E02   Shyam   56      NaN
2    E03   Rahul   23  34000.0
3    E04  Vishal   44  30000.0
4    E05    Ravi   32      NaN
5    E06    John   36  62000.0

In [141]:
print(pd.merge(df1,df2,on = "Emp Id", how = "right"))

  Emp Id   Names   Age  Salary
0    E01     Ram  34.0   45000
1    E07     NaN   NaN   56000
2    E03   Rahul  23.0   34000
3    E04  Vishal  44.0   30000
4    E08     NaN   NaN   50000
5    E06    John  36.0   62000

In [147]:
data1 = {"Emp Id": ["E01","E02","E03","E04","E05","E06"],
        "Names":["Ram","Shyam","Rahul","Vishal","Ravi","John"],
        "Age":[34,56,23,44,32,36]}

data2 = {"Emp Id": ["E07","E08","E09","E10","E11","E12"],
        "Names":["bittu","chintu","pappu","chotu","bunty","golu"],
        "Age":[34,56,23,44,32,36]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [148]:
print(pd.concat([df1,df2]))

  Emp Id   Names  Age
0    E01     Ram   34
1    E02   Shyam   56
2    E03   Rahul   23
3    E04  Vishal   44
4    E05    Ravi   32
5    E06    John   36
0    E07   bittu   34
1    E08  chintu   56
2    E09   pappu   23
3    E10   chotu   44
4    E11   bunty   32
5    E12    golu   36

## Compare DataFrames

In [21]:
dict = {"Fruits": ["mango","apples","banana","papaya"],
       "Price": [100,150,50,35],
       "Quantity":[15,10,10,3]}
df1 = pd.DataFrame(dict)
print(df1)
df2 = df1.copy()

df2.loc[0,"Price"] = 120
df2.loc[1,"Price"] = 175
df2.loc[3,"Price"] = 30
df2.loc[0,"Quantity"] = 12
df2.loc[1,"Quantity"] = 15
df2.loc[3,"Quantity"] = 5
print(df2)

print(df1.compare(df2,align_axis = 0))

   Fruits  Price  Quantity
0   mango    100        15
1  apples    150        10
2  banana     50        10
3  papaya     35         3
   Fruits  Price  Quantity
0   mango    120        12
1  apples    175        15
2  banana     50        10
3  papaya     30         5
         Price  Quantity
0 self   100.0      15.0
  other  120.0      12.0
1 self   150.0      10.0
  other  175.0      15.0
3 self    35.0       3.0
  other   30.0       5.0

In [25]:
print(df1.compare(df2))

   Price        Quantity
    self  other     self other
0  100.0  120.0     15.0  12.0
1  150.0  175.0     10.0  15.0
3   35.0   30.0      3.0   5.0

In [27]:
print(df1.compare(df2,keep_equal= False))

   Price        Quantity
    self  other     self other
0  100.0  120.0     15.0  12.0
1  150.0  175.0     10.0  15.0
3   35.0   30.0      3.0   5.0

In [28]:
print(df1.compare(df2,keep_shape= True))

  Fruits        Price        Quantity
    self other   self  other     self other
0    NaN   NaN  100.0  120.0     15.0  12.0
1    NaN   NaN  150.0  175.0     10.0  15.0
2    NaN   NaN    NaN    NaN      NaN   NaN
3    NaN   NaN   35.0   30.0      3.0   5.0

## Pandas Pivoting and Melting DataFrames

In [43]:
dict= {"Keys": ["k1","k2","k1","k2"],
      "Names": ["John","Ben","David","Peter"],
      "Houses": ["red","blue","green","red"],
      "Grades": ["3rd","8th","9th","8th"]}
df = pd.DataFrame(dict)
print(df)
df.pivot(index="Keys", columns="Names", values=["Houses","Grades"])

  Keys  Names Houses Grades
0   k1   John    red    3rd
1   k2    Ben   blue    8th
2   k1  David  green    9th
3   k2  Peter    red    8th

      Houses                   Grades
Names    Ben  David John Peter    Ben David John Peter
Keys
k1       NaN  green  red   NaN    NaN   9th  3rd   NaN
k2      blue    NaN  NaN   red    8th   NaN  NaN   8th

### Melting

In [44]:
dict= {"Names": ["John","Ben","David","Peter"],
      "Houses": ["red","blue","green","red"],
      "Grades": ["3rd","8th","9th","8th"]}
df= pd.DataFrame(dict)
print(df)

   Names Houses Grades
0   John    red    3rd
1    Ben   blue    8th
2  David  green    9th
3  Peter    red    8th

In [57]:
print(df.melt("Names",["Houses","Grades"],"House&Grades"))

   Names House&Grades  value
0   John       Houses    red
1    Ben       Houses   blue
2  David       Houses  green
3  Peter       Houses    red
4   John       Grades    3rd
5    Ben       Grades    8th
6  David       Grades    9th
7  Peter       Grades    8th